#!/bin/bash
CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
if [ ${CAN_I_RUN_SUDO} -gt 0 ]
then
    ps -ef | grep fekit | awk '{print $2}' | xargs sudo kill -9
    sudo nohup fekit-server > server.log 2>&1 &
else
    echo "please use sudo"
fi
